[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "6gweAUcgHUfiUkD2SPGpE7MBjh8hQ7mPZG5iQrBqP46n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/samfior/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
